#!/usr/bin/env python3
"""
measure_policy.py — Teacher-forcing policy measurement for chess models.

For each row in a rollout JSONL (already generated), re-scores:
  • All legal moves at each board position (unnormalized log-probs + per-token breakdown)
  • The thinking block token-by-token (SFT/RL only)

Output: one parquet row per (jsonl_row, turn) with the full probability matrix.

Usage:
  python measure_policy.py \
    --model-type sft \
    --model-path /path/to/hf_checkpoint \
    --rollout-data /path/to/0.jsonl \
    --parquet-dir  /path/to/eval_parquets \
    --output-path  /path/to/raw_scores.parquet \
    --batch-size   256
"""

import argparse
import ast
import json
import os
from pathlib import Path
from typing import Optional

import chess
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from tqdm import tqdm

# ─────────────────────────────────────────────────────────────────────────────
# Vocabulary / tokenization utilities
# ─────────────────────────────────────────────────────────────────────────────

import re

FILES = "abcdefgh"
RANKS  = "12345678"
SQUARES = {f + r for f in FILES for r in RANKS}


def stored_text_to_ids(text: str, vocab: dict) -> list:
    """
    Convert stored JSONL text (space-separated, intra-move tokens concatenated)
    back to a list of token IDs.

    The decoder in LanTokenizer concatenates tokens within a single move without
    spaces, and separates moves with spaces.  For example:
      [N, g1, f3] is stored as "Ng1f3"  (not "N g1 f3")
      [P, d4, x, e5] is stored as "Pd4xe5"
      [<T>] is stored as "<T>"
    """
    ids = []
    for word in text.split():
        ids.extend(_word_to_ids(word, vocab))
    return ids


def _word_to_ids(word: str, vocab: dict) -> list:
    if word in vocab:
        return [vocab[word]]
    # Castling with check suffix: O-O+, O-O-O#, etc.
    if word.startswith("O-O"):
        base = "O-O-O" if word.startswith("O-O-O") else "O-O"
        ids = [vocab[base]]
        for ch in word[len(base):]:
            if ch in vocab:
                ids.append(vocab[ch])
        return ids
    # Regular LAN move — greedy parse: try 2-char (squares) then 1-char
    ids, i = [], 0
    while i < len(word):
        two = word[i : i + 2]
        if two in vocab:
            ids.append(vocab[two]); i += 2
        elif word[i] in vocab:
            ids.append(vocab[word[i]]); i += 1
        else:
            i += 1  # skip unknown character
    return ids


def ids_to_lan(token_ids: list, id2tok: dict) -> str:
    """Concatenate vocab strings for a move token ID sequence."""
    return "".join(id2tok.get(t, "?") for t in token_ids)


def _lan_word_to_uci(word: str, board: chess.Board) -> Optional[str]:
    """
    Convert a single concatenated LAN word (e.g. 'Ng1f3', 'Pd4xe5', 'O-O') to UCI.
    Returns None if the word doesn't parse as a move.
    """
    word_clean = word.rstrip("+#")
    if word_clean in {"O-O", "O-O-O"}:
        for mv in board.legal_moves:
            if board.is_castling(mv):
                dest_file = chess.square_file(mv.to_square)
                if word_clean == "O-O" and dest_file == 6:
                    return mv.uci()
                if word_clean == "O-O-O" and dest_file == 2:
                    return mv.uci()
        return None
    m = re.match(r"^[KQRBNP]([a-h][1-8])(?:x)?([a-h][1-8])(?:=([QRBN]))?[+#]?$", word)
    if not m:
        return None
    frm, to, promo = m.groups()
    return frm + to + (promo.lower() if promo else "")


def fen_from_lan_input(input_text: str) -> str:
    """
    Simulate all LAN moves in a JSONL input string to obtain the resulting FEN.
    The input is space-separated concatenated LAN words (e.g. 'Ng1f3 Pd7d5 ...<T>').
    Everything at and after <T> is ignored.
    Assumes games start from the standard initial position.
    """
    board = chess.Board()
    for word in input_text.split():
        if word.startswith("<"):   # special token (<T>, <bos>, etc.)
            break
        uci = _lan_word_to_uci(word, board)
        if uci:
            try:
                board.push(chess.Move.from_uci(uci))
            except Exception:
                break   # malformed — stop here
    return board.fen()


def legal_moves_with_tokens(board: chess.Board, vocab: dict) -> list:
    """
    Returns [(uci_str, token_id_list)] for all legal moves on the board.

    check/checkmate suffixes (+/#) are intentionally excluded: they are
    generated by the model AFTER the move tokens and are not part of the
    move's log-prob.
    """
    result = []
    for mv in board.legal_moves:
        uci = mv.uci()
        if board.is_castling(mv):
            base = "O-O" if chess.square_file(mv.to_square) == 6 else "O-O-O"
            toks = [vocab[base]]
        else:
            piece = board.piece_at(mv.from_square).symbol().upper()
            frm   = chess.square_name(mv.from_square)
            to    = chess.square_name(mv.to_square)
            toks  = [vocab[piece], vocab[frm]]
            if board.is_capture(mv):
                toks.append(vocab["x"])
            toks.append(vocab[to])
            if mv.promotion:
                toks += [vocab["="], vocab[chess.piece_symbol(mv.promotion).upper()]]
        result.append((uci, toks))
    return result


def uci_from_lan_token_ids(token_ids: list, id2tok: dict, board_before: chess.Board) -> Optional[str]:
    """Convert a LAN token ID sequence back to a UCI move string."""
    lan = ids_to_lan(token_ids, id2tok)
    for mv in board_before.legal_moves:
        if board_before.is_castling(mv):
            base = "O-O" if chess.square_file(mv.to_square) == 6 else "O-O-O"
            if lan.startswith(base):
                return mv.uci()
        else:
            piece = board_before.piece_at(mv.from_square).symbol().upper()
            frm   = chess.square_name(mv.from_square)
            to    = chess.square_name(mv.to_square)
            cap   = "x" if board_before.is_capture(mv) else ""
            promo = ("=" + chess.piece_symbol(mv.promotion).upper()) if mv.promotion else ""
            expected = f"{piece}{frm}{cap}{to}{promo}"
            if lan.startswith(expected):
                return mv.uci()
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Model loading
# ─────────────────────────────────────────────────────────────────────────────

def load_model_and_vocab(model_type: str, model_path: str, config_path: Optional[str], device: str):
    """
    Returns (model, vocab, bos_id, id2tok).

    All three model types (pretrain, sft, rl) are stored as standard HuggingFace
    checkpoints with a vocab.json alongside the weights.  Pretrain models have a
    smaller vocab (81 tokens, no <T>/<call_env>) but are otherwise loaded
    identically to SFT/RL models.
    """
    from transformers import AutoModelForCausalLM

    vocab_json = Path(model_path) / "vocab.json"
    with open(vocab_json) as f:
        vocab = json.load(f)
    bos_id = vocab["<bos>"]

    model = AutoModelForCausalLM.from_pretrained(
        model_path, trust_remote_code=True, torch_dtype=torch.bfloat16
    ).to(device)
    model.eval()

    id2tok = {v: k for k, v in vocab.items()}
    return model, vocab, bos_id, id2tok


# ─────────────────────────────────────────────────────────────────────────────
# Scoring functions
# ─────────────────────────────────────────────────────────────────────────────

def _kv_to_legacy(kv):
    """
    Normalize a past_key_values value to a legacy tuple-of-(K,V) layout we can
    slice/expand. transformers ≥4.42 returns a Cache object; older versions
    returned the legacy tuple directly. Cache exposes .to_legacy_cache() and
    is also iterable as (K,V) per layer, so this works either way.
    """
    if isinstance(kv, tuple):
        return kv
    return kv.to_legacy_cache()


def _kv_from_legacy(kv):
    """Wrap a legacy tuple-of-(K,V) in DynamicCache for newer transformers."""
    from transformers.cache_utils import DynamicCache
    return DynamicCache.from_legacy_cache(kv)


@torch.no_grad()
def score_moves_kvcache(
    model,
    ctx_ids: list,
    move_token_lists: list,
    device: str,
) -> tuple:
    """
    Score all legal moves against a shared context using batched KV cache.

    Returns:
      scores         : list[float]        — Σ log p per move
      per_tok_scores : list[list[float]]  — per-token log p per move

    Algorithm:
      1. One forward pass over the context → KV cache + last-position logits.
      2. Token 0 of every move: read directly from those logits (free).
      3. Token j (j ≥ 1): batch ALL moves that still have a j-th token into a
         single forward pass against the shared KV cache, expanded to batch N.
         Moves that are shorter than j+1 tokens drop out of the active set.

    This reduces sequential forward passes from N×(max_len-1) to (max_len-1),
    at the cost of O(N×ctx_len) KV cache memory (N≈30 moves, ctx_len≈330).

    KV cache is converted to legacy tuple form internally (so we can slice the
    batch dim cleanly) and re-wrapped in DynamicCache before each model call —
    transformers ≥4.50 / Qwen3 only accept Cache objects on the input side.
    """
    if not move_token_lists:
        return [], []

    N = len(move_token_lists)
    max_len = max(len(mv) for mv in move_token_lists)

    # ── Step 1: context forward pass ─────────────────────────────────────────
    ctx_t   = torch.tensor([ctx_ids], dtype=torch.long, device=device)
    ctx_out = model(ctx_t, use_cache=True)
    kv_ctx  = _kv_to_legacy(ctx_out.past_key_values)               # [(K,V)×layers], each [1,H,T,D]
    log_last = F.log_softmax(ctx_out.logits[0, -1, :], dim=-1)    # [vocab]

    # ── Step 2: token 0 — free from context logit ───────────────────────────
    per_tok_scores = [[None] * len(mv) for mv in move_token_lists]
    for i, mv in enumerate(move_token_lists):
        per_tok_scores[i][0] = log_last[mv[0]].item()

    if max_len == 1:
        scores = [per_tok_scores[i][0] for i in range(N)]
        return scores, per_tok_scores

    # ── Step 3+: batched forward passes, one per token position ──────────────
    # Expand KV cache from batch=1 to batch=N so all moves can share it.
    active_global = list(range(N))
    active_kv = tuple(
        (k.expand(N, -1, -1, -1).contiguous(), v.expand(N, -1, -1, -1).contiguous())
        for k, v in kv_ctx
    )

    for tok_pos in range(1, max_len):
        # Which moves in the current active set still need a token at tok_pos?
        still_local  = [j for j, i in enumerate(active_global)
                         if tok_pos < len(move_token_lists[i])]
        still_global = [active_global[j] for j in still_local]
        if not still_global:
            break

        # Input: previous token for each still-active move  [M, 1]
        inp = torch.tensor(
            [[move_token_lists[i][tok_pos - 1]] for i in still_global],
            dtype=torch.long, device=device,
        )

        # Select KV entries for only the still-active batch slots
        sel_kv = tuple(
            (k[still_local], v[still_local])
            for k, v in active_kv
        )

        out       = model(inp, past_key_values=_kv_from_legacy(sel_kv), use_cache=True)
        log_probs = F.log_softmax(out.logits[:, 0, :], dim=-1)    # [M, vocab]

        for batch_j, move_i in enumerate(still_global):
            target = move_token_lists[move_i][tok_pos]
            per_tok_scores[move_i][tok_pos] = log_probs[batch_j, target].item()

        active_global = still_global
        active_kv     = _kv_to_legacy(out.past_key_values)

    scores = [sum(per_tok_scores[i]) for i in range(N)]
    return scores, per_tok_scores


@torch.no_grad()
def batch_score_thinking(
    model,
    input_ids: list,
    thinking_id_lists: list,
    device: str,
    batch_size: int = 16,
) -> list:
    """
    Score K thinking blocks against the same context (input_ids) in batched
    forward passes.

    All K rows of one puzzle share input_ids (same game history), but each has
    a different thinking block.  Instead of K sequential single-sample forward
    passes we pack them into ceil(K/batch_size) padded batched passes.

    Full sequences are right-padded.  Because attention is causal, padding on
    the right does not affect log-probs at valid token positions.

    Returns: list of K lists, each containing per-token log probs for that
             row's thinking block.  Empty list for rows with no thinking tokens.
    """
    K = len(thinking_id_lists)
    results: list = [[] for _ in range(K)]

    valid = [(i, tids) for i, tids in enumerate(thinking_id_lists) if tids]
    if not valid:
        return results

    ctx_len = len(input_ids)

    for sub_start in range(0, len(valid), batch_size):
        sub      = valid[sub_start : sub_start + batch_size]
        B        = len(sub)
        seqs     = [input_ids + tids for _, tids in sub]
        max_len  = max(len(s) for s in seqs)

        # Right-padded input (right-shifted for LM: feed seq[:-1], label seq[1:])
        inp  = torch.zeros(B, max_len - 1, dtype=torch.long, device=device)
        mask = torch.zeros(B, max_len - 1, dtype=torch.long, device=device)
        for b, seq in enumerate(seqs):
            n = len(seq) - 1
            inp[b, :n]  = torch.tensor(seq[:-1])
            mask[b, :n] = 1

        logits = model(input_ids=inp, attention_mask=mask).logits  # [B, max_len-1, vocab]
        lps    = F.log_softmax(logits, dim=-1)

        for b, (orig_i, tids) in enumerate(sub):
            results[orig_i] = [
                lps[b, ctx_len - 1 + j, tid].item()
                for j, tid in enumerate(tids)
            ]

    return results


# ─────────────────────────────────────────────────────────────────────────────
# Row parsing
# ─────────────────────────────────────────────────────────────────────────────

def parse_row(row: dict, vocab: dict, bos_id: int, model_type: str) -> dict:
    """
    Parse a JSONL rollout row into structured fields.

    Returns dict with keys:
      input_ids       : list[int] — prompt token IDs (with BOS prepended)
      thinking_ids    : list[int] — thinking block token IDs (SFT/RL only)
      t_end_id        : int       — </T> token ID
      call_env_id     : int       — <call_env> token ID
      model_turns     : list of {token_ids, lan_str}  — model's generated moves
      env_turns       : list of {token_ids}            — env's moves
    """
    input_ids    = [bos_id] + stored_text_to_ids(row["input"], vocab)
    t_end_id     = vocab.get("</T>", -1)
    call_env_id  = vocab.get("<call_env>", -1)

    output = row.get("output", "")
    thinking_ids = []

    if model_type != "pretrain" and "</T>" in output:
        thinking_text   = output[: output.index("</T>")]
        move_seq_text   = output[output.index("</T>") + len("</T>") :].strip()
        thinking_ids    = stored_text_to_ids(thinking_text, vocab)
    else:
        move_seq_text = output

    # Split on <call_env> → alternating model/env segments
    segments   = move_seq_text.split("<call_env>")
    model_turns, env_turns = [], []
    for i, seg in enumerate(segments[:-1]):
        toks = stored_text_to_ids(seg.strip(), vocab)
        if i % 2 == 0:
            model_turns.append({"token_ids": toks})
        else:
            env_turns.append({"token_ids": toks})

    return {
        "input_ids":    input_ids,
        "thinking_ids": thinking_ids,
        "t_end_id":     t_end_id,
        "call_env_id":  call_env_id,
        "model_turns":  model_turns,
        "env_turns":    env_turns,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Parquet lookup (for FEN, env_replies, puzzle metadata)
# ─────────────────────────────────────────────────────────────────────────────

def build_parquet_lookup(parquet_dir: str, data_sources: set) -> dict:
    """
    Load all relevant parquet files and build a lookup:
      {(data_source, fen): extra_info_dict}

    Key is (data_source, FEN) — the board state at the start of the model's
    first move.  This is the only reliable unique key shared between the
    parquet (extra_info['FEN']) and the JSONL (reconstructed from input tokens).
    """
    lookup = {}
    parquet_dir = Path(parquet_dir)
    for ds in data_sources:
        candidates = [
            parquet_dir / f"{ds}_multi_turn.parquet",
            parquet_dir / f"{ds}.parquet",
        ]
        found = next((p for p in candidates if p.exists()), None)
        if found is None:
            print(f"  WARNING: no parquet found for data_source={ds!r} in {parquet_dir}")
            continue
        df = pd.read_parquet(found)
        for _, row in df.iterrows():
            ei  = row["extra_info"]
            fen = ei["FEN"] if isinstance(ei, dict) else dict(ei)["FEN"]
            key = (row["data_source"], fen)
            lookup[key] = ei
    return lookup


# ─────────────────────────────────────────────────────────────────────────────
# Main processing loop
# ─────────────────────────────────────────────────────────────────────────────

def _score_one_row(
    row_idx: int,
    row: dict,
    parsed: dict,
    trace_per_tok: list,
    ei: dict,
    puzzle_id: str,
    model,
    vocab: dict,
    id2tok: dict,
    model_type: str,
    model_path: str,
    device: str,
) -> tuple:
    """
    Score all legal moves for every turn of one rollout row.
    Returns (records_list, ok: bool).
    """
    fen_start   = ei.get("FEN", "")
    env_replies = list(ei.get("env_replies", []))
    rating      = ei.get("Rating", None)
    gt_moves    = ast.literal_eval(row["ground_truth"])

    input_ids    = parsed["input_ids"]
    thinking_ids = parsed["thinking_ids"]
    t_end_id     = parsed["t_end_id"]
    call_env_id  = parsed["call_env_id"]
    model_turns  = parsed["model_turns"]

    try:
        board = chess.Board(fen_start)
    except Exception:
        return [], False

    cond_ctx = list(input_ids)
    if model_type != "pretrain":
        cond_ctx = cond_ctx + thinking_ids + ([t_end_id] if t_end_id >= 0 else [])

    records = []
    for turn_idx, gt_uci in enumerate(gt_moves):
        legal      = legal_moves_with_tokens(board, vocab)
        uci_list   = [u for u, _ in legal]
        move_toks  = [t for _, t in legal]
        move_lans  = [ids_to_lan(t, id2tok) for t in move_toks]

        gen_toks   = model_turns[turn_idx]["token_ids"] if turn_idx < len(model_turns) else []
        parsed_uci = uci_from_lan_token_ids(gen_toks, id2tok, board)

        scores, per_tok_scores = score_moves_kvcache(model, cond_ctx, move_toks, device)

        records.append({
            "row_idx":                row_idx,
            "puzzle_id":              puzzle_id,
            "data_source":            row["data_source"],
            "prompt":                 row.get("input", ""),
            "model_type":             model_type,
            "model_path":             model_path,
            "turn":                   turn_idx,
            "outcome":                float(row.get("outcome_score", row.get("score", 0))),
            "rating":                 rating,
            "fen":                    board.fen(),
            "gt_uci":                 gt_uci,
            "parsed_move_uci":        parsed_uci,
            "legal_moves_uci":        uci_list,
            "legal_moves_lan":        move_lans,
            "legal_moves_token_ids":  move_toks,
            "log_pi_tilde":           scores,
            "log_pi_tilde_per_token": per_tok_scores,
            "context_token_ids":      cond_ctx,
            "thinking_token_ids":     thinking_ids if model_type != "pretrain" else None,
            "log_pi_trace_per_token": trace_per_tok if model_type != "pretrain" else None,
            "log_pi_trace":           sum(trace_per_tok) if trace_per_tok else None,
            "thinking_len":           len(thinking_ids),
        })

        try:
            board.push(chess.Move.from_uci(gt_uci))
        except Exception:
            break

        if turn_idx < len(gt_moves) - 1:
            gt_move_toks = next((t for u, t in legal if u == gt_uci), gen_toks)
            cond_ctx = cond_ctx + gt_move_toks + ([call_env_id] if call_env_id >= 0 else [])

            if turn_idx < len(env_replies):
                env_lan  = env_replies[turn_idx]
                env_toks = stored_text_to_ids(env_lan, vocab)
                cond_ctx = cond_ctx + env_toks

                env_uci = None
                for mv in board.legal_moves:
                    if board.is_castling(mv):
                        base = "O-O" if chess.square_file(mv.to_square) == 6 else "O-O-O"
                        if env_lan.rstrip("+#").startswith(base):
                            env_uci = mv.uci(); break
                    else:
                        piece = board.piece_at(mv.from_square).symbol().upper()
                        frm   = chess.square_name(mv.from_square)
                        to    = chess.square_name(mv.to_square)
                        cap   = "x" if board.is_capture(mv) else ""
                        promo = ("=" + chess.piece_symbol(mv.promotion).upper()) if mv.promotion else ""
                        if env_lan.rstrip("+#").startswith(f"{piece}{frm}{cap}{to}{promo}"):
                            env_uci = mv.uci(); break
                if env_uci:
                    try:
                        board.push(chess.Move.from_uci(env_uci))
                    except Exception:
                        break

    return records, True


def process(args):
    device = args.device if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    # ── Load rollout JSONL ──────────────────────────────────────────────────
    print(f"Loading rollout data: {args.rollout_data}")
    with open(args.rollout_data) as f:
        rows = [json.loads(line) for line in f]
    print(f"  {len(rows)} rows loaded")
    if args.num_shards > 1:
        if not (0 <= args.shard_idx < args.num_shards):
            raise ValueError(f"shard_idx={args.shard_idx} out of range for num_shards={args.num_shards}")
        rows = [r for i, r in enumerate(rows) if i % args.num_shards == args.shard_idx]
        print(f"  shard {args.shard_idx}/{args.num_shards}: kept {len(rows)} rows")

    # ── Build parquet lookup ────────────────────────────────────────────────
    data_sources = {r["data_source"] for r in rows}
    print(f"Data sources: {data_sources}")
    lookup = build_parquet_lookup(args.parquet_dir, data_sources)
    print(f"  {len(lookup)} puzzles in parquet lookup")

    # ── Load model + vocab ──────────────────────────────────────────────────
    print(f"Loading {args.model_type} model from {args.model_path}")
    model, vocab, bos_id, id2tok = load_model_and_vocab(
        args.model_type, args.model_path, args.config_path, device
    )
    print(f"  Vocab size: {len(vocab)}, BOS={bos_id}")

    # ── Group rows by puzzle (same FEN → same input_ids → can share thinking
    #    batch scoring) ────────────────────────────────────────────────────────
    from collections import defaultdict
    puzzle_groups: dict = defaultdict(list)
    for row_idx, row in enumerate(rows):
        fen = fen_from_lan_input(row["input"])
        key = (row["data_source"], fen)
        puzzle_groups[key].append((row_idx, row))

    records = []
    skipped = 0

    for key, puzzle_row_list in tqdm(puzzle_groups.items(), desc="Scoring puzzles"):
        extra_info = lookup.get(key)
        if extra_info is None:
            skipped += len(puzzle_row_list)
            continue

        ei = extra_info if isinstance(extra_info, dict) else dict(extra_info)
        puzzle_id = ei.get("PuzzleId", f"puzzle_{key[0]}_{key[1][:8]}")

        # input_ids is identical for all rows of a puzzle (same game history)
        _, first_row = puzzle_row_list[0]
        input_ids = [bos_id] + stored_text_to_ids(first_row["input"], vocab)

        # Parse all rows of this puzzle
        parsed_list = [
            (row_idx, row, parse_row(row, vocab, bos_id, args.model_type))
            for row_idx, row in puzzle_row_list
        ]

        # ── Batch-score all thinking blocks for this puzzle in one GPU pass ──
        # All K rows share input_ids; their thinking blocks differ.
        # batch_score_thinking packs them into ceil(K/batch_size) padded passes
        # instead of K sequential single-sample forward passes.
        if args.model_type != "pretrain":
            thinking_id_lists = [p[2]["thinking_ids"] for p in parsed_list]
            trace_per_tok_list = batch_score_thinking(
                model, input_ids, thinking_id_lists, device, args.batch_size
            )
        else:
            trace_per_tok_list = [[] for _ in parsed_list]

        # ── Per-row move scoring ─────────────────────────────────────────────
        for (row_idx, row, parsed), trace_per_tok in zip(parsed_list, trace_per_tok_list):
            row_records, ok = _score_one_row(
                row_idx, row, parsed, trace_per_tok, ei, puzzle_id,
                model, vocab, id2tok, args.model_type, args.model_path, device,
            )
            if ok:
                records.extend(row_records)
            else:
                skipped += 1

    print(f"\nDone. {len(records)} records written, {skipped} rows skipped.")

    out_path = Path(args.output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(records).to_parquet(out_path, index=False)
    print(f"Saved to {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model-type",   required=True, choices=["pretrain", "sft", "rl"])
    p.add_argument("--model-path",   required=True)
    p.add_argument("--config-path",  default=None, help="YAML config (pretrain only)")
    p.add_argument("--rollout-data", required=True, help="Path to 0.jsonl rollout file")
    p.add_argument("--parquet-dir",  required=True,
                   help="Directory containing eval parquets (e.g. eval_thinking/)")
    p.add_argument("--output-path",  required=True, help="Output .parquet path")
    p.add_argument("--shard-idx",    type=int, default=0,
                    help="Process only rows where row_idx %% num_shards == shard_idx (0-indexed)")
    p.add_argument("--num-shards",   type=int, default=1,
                    help="Total number of shards; 1 = no sharding (default)")
    p.add_argument("--batch-size",   type=int, default=256,
                   help="Micro-batch size for batched scoring (short contexts)")
    p.add_argument("--device",       default="cuda")
    return p.parse_args()


if __name__ == "__main__":
    process(parse_args())
